DROP TABLE MEMBER2 cascade ;
DROP TABLE ORDERS2 cascade ;
DROP TABLE DELIVERY2 cascade ;
DROP TABLE ORDER_ITEM2 cascade ;
DROP TABLE ITEM2 cascade ;

CREATE TABLE MEMBER2 (
	ID	BIGINT	NOT NULL,
	NAME	VARCHAR(30)	NOT NULL,
	CITY	VARCHAR(30)	NULL,
	STREET	VARCHAR(30)	NULL,
	ZIPCODE	VARCHAR(10)	NULL
);


CREATE TABLE ORDERS2 (
	ID	BIGINT	NOT NULL,
	MEMBER_ID	BIGINT	NOT NULL,
	DELIVERY_ID	BIGINT	NOT NULL,
	ORDER_DATE	TIMESTAMP	NOT NULL,
	STATUS	INTEGER	NOT NULL
);


CREATE TABLE DELIVERY2 (
	ID	BIGINT	NOT NULL,
	STATUS	INTEGER	NOT NULL,
	CITY	VARCHAR(30)	NOT NULL,
	STREET	VARCHAR(30)	NOT NULL,
	ZIPCODE	VARCHAR(10)	NOT NULL
);


CREATE TABLE ORDER_ITEM2 (
	ID	BIGINT	NOT NULL,
	ORDER_ID	BIGINT	NOT NULL,
	ITEM_ID	BIGINT	NOT NULL,
	ORDER_PRICE	INTEGER	NOT NULL,
	COUNT	INTEGER	NOT NULL
);


CREATE TABLE ITEM2 (
	ID	BIGINT	NOT NULL,
	NAME	VARCHAR(30)	NOT NULL,
	PRICE	INTEGER	NOT NULL,
	STOCK_QUANTITY	INTEGER	NOT NULL
);

ALTER TABLE MEMBER2 ADD CONSTRAINT PK_MEMBER2 PRIMARY KEY (
	ID
);

ALTER TABLE ORDERS2 ADD CONSTRAINT PK_ORDERS2 PRIMARY KEY (
	ID
);

ALTER TABLE DELIVERY2 ADD CONSTRAINT PK_DELIVERY2 PRIMARY KEY (
	ID
);

ALTER TABLE ORDER_ITEM2 ADD CONSTRAINT PK_ORDER_ITEM2 PRIMARY KEY (
	ID
);

ALTER TABLE ITEM2 ADD CONSTRAINT PK_ITEM2 PRIMARY KEY (
	ID
);

ALTER TABLE ORDERS2 ADD CONSTRAINT FK_MEMBER2_TO_ORDERS2_1 FOREIGN KEY (
	MEMBER_ID
)
REFERENCES MEMBER2 (
	ID
);

ALTER TABLE ORDERS2 ADD CONSTRAINT FK_DELIVERY2_TO_ORDERS2_1 FOREIGN KEY (
	DELIVERY_ID
)
REFERENCES DELIVERY2 (
	ID
);

ALTER TABLE ORDER_ITEM2 ADD CONSTRAINT FK_ORDERS2_TO_ORDER_ITEM2_1 FOREIGN KEY (
	ORDER_ID
)
REFERENCES ORDERS2 (
	ID
);

ALTER TABLE ORDER_ITEM2 ADD CONSTRAINT FK_ITEM2_TO_ORDER_ITEM2_1 FOREIGN KEY (
	ITEM_ID
)
REFERENCES ITEM2 (
	ID
);

